# Generated by Django 2.0.6 on 2020-07-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='expired_day_num',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
    ]
