# Generated by Django 2.0.6 on 2020-07-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_receipt', '0002_auto_20200707_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='name',
        ),
    ]
