# Generated by Django 2.0.6 on 2020-07-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_receipt', '0003_remove_goodsreceipt_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='expired_at',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='expired_date',
            field=models.DateField(null=True),
        ),
    ]
