# Generated by Django 2.0.6 on 2020-07-07 11:20

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flower', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('flower', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='order_detail_flower', to='flower.Flower')),
                ('order', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='order_detail_order', to='order.Order')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
