# Generated by Django 2.0.6 on 2020-07-07 11:20

from django.db import migrations, models
import django.db.models.expressions
import flower.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flower_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('detail', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=191)),
                ('is_deleted', models.BooleanField(default=False)),
                ('flower_category', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='flower_category', to='flower_category.FlowerCategory')),
            ],
            options={
                'db_table': 'flower',
            },
        ),
        migrations.CreateModel(
            name='FlowerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=False)),
                ('url', models.ImageField(upload_to=flower.models.FlowerImage._get_file_path)),
                ('flower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, related_name='flower', to='flower.Flower')),
            ],
            options={
                'db_table': 'flower_image',
            },
        ),
    ]
