# Generated by Django 2.0.6 on 2020-07-06 17:48

import django.contrib.auth.models
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=191, null=True)),
                ('last_name', models.CharField(blank=True, max_length=191, null=True)),
                ('address', models.CharField(blank=True, max_length=191, null=True)),
                ('is_verified_email', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=191)),
                ('last_reset_password_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('stripe_account', models.CharField(blank=True, max_length=191, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=user.models.User._get_file_path)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
