# Generated by Django 2.0.6 on 2020-07-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-06-14 22:23:28.301848'),
            preserve_default=False,
        ),
    ]
