# Generated by Django 2.0.6 on 2020-07-06 17:48

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateField()),
                ('address', models.CharField(max_length=191)),
                ('COD', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='shipping_order', to='order.Order')),
            ],
            options={
                'db_table': 'shipping',
            },
        ),
    ]
