# Generated by Django 2.0.6 on 2020-07-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='COD',
        ),
    ]
